# Generated by Django 2.1.7 on 2019-05-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LRS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
